# The Curse of the Baskervilles

“I have in my pocket a manuscript,” said Dr. James Mortimer.

“I observed it as you entered the room,” said Holmes.

“It is an old manuscript.”

“Early eighteenth century, unless it is a forgery.”

“How can you say that, sir?”

“You have presented an inch or two of it to my examination all
      the time that you have been talking. It would be a poor expert
      who could not give the date of a document within a decade or so.
      You may possibly have read my little monograph upon the subject.
      I put that at 1730.”

“The exact date is 1742.” Dr. Mortimer drew it from his
      breast-pocket. “This family paper was committed to my care by Sir
      Charles Baskerville, whose sudden and tragic death some three
      months ago created so much excitement in Devonshire. I may say
      that I was his personal friend as well as his medical attendant.
      He was a strong-minded man, sir, shrewd, practical, and as
      unimaginative as I am myself. Yet he took this document very
      seriously, and his mind was prepared for just such an end as did
      eventually overtake him.”

Holmes stretched out his hand for the manuscript and flattened it
      upon his knee. “You will observe, Watson, the alternative use of
      the long _s_ and the short. It is one of several indications
      which enabled me to fix the date.”

I looked over his shoulder at the yellow paper and the faded
      script. At the head was written: “Baskerville Hall,” and below in
      large, scrawling figures: “1742.”

“It appears to be a statement of some sort.”

“Yes, it is a statement of a certain legend which runs in the
      Baskerville family.”

“But I understand that it is something more modern and practical
      upon which you wish to consult me?”

“Most modern. A most practical, pressing matter, which must be
      decided within twenty-four hours. But the manuscript is short and
      is intimately connected with the affair. With your permission I
      will read it to you.”

Holmes leaned back in his chair, placed his finger-tips together,
      and closed his eyes, with an air of resignation. Dr. Mortimer
      turned the manuscript to the light and read in a high, cracking
      voice the following curious, old-world narrative:

“Of the origin of the Hound of the Baskervilles there have been
        many statements, yet as I come in a direct line from Hugo
        Baskerville, and as I had the story from my father, who also
        had it from his, I have set it down with all belief that it
        occurred even as is here set forth. And I would have you
        believe, my sons, that the same Justice which punishes sin may
        also most graciously forgive it, and that no ban is so heavy
        but that by prayer and repentance it may be removed.  Learn
        then from this story not to fear the fruits of the past, but
        rather to be circumspect in the future, that those foul
        passions whereby our family has suffered so grievously may not
        again be loosed to our undoing.

“Know then that in the time of the Great Rebellion (the
history of which by the learned Lord Clarendon I most
            earnestly commend to your attention) this Manor of
            Baskerville was held by Hugo of that name, nor can it be
            gainsaid that he was a most wild, profane, and godless man.
             This, in truth, his neighbours might have pardoned, seeing
            that saints have never flourished in those parts, but there
            was in him a certain wanton and cruel humour which made his
            name a by-word through the West.  It chanced that this Hugo
            came to love (if, indeed, so dark a passion may be known
            under so bright a name) the daughter of a yeoman who held
            lands near the Baskerville estate. But the young maiden,
            being discreet and of good repute, would ever avoid him,
            for she feared his evil name.  So it came to pass that one
            Michaelmas this Hugo, with five or six of his idle and
            wicked companions, stole down upon the farm and carried off
            the maiden, her father and brothers being from home, as he
            well knew.  When they had brought her to the Hall the
            maiden was placed in an upper chamber, while Hugo and his
            friends sat down to a long carouse, as was their nightly
            custom.  Now, the poor lass upstairs was like to have her
            wits turned at the singing and shouting and terrible oaths
            which came up to her from below, for they say that the
            words used by Hugo Baskerville, when he was in wine, were
            such as might blast the man who said them.  At last in the
            stress of her fear she did that which might have daunted
            the bravest or most active man, for by the aid of the
            growth of ivy which covered (and still covers) the south
            wall she came down from under the eaves, and so homeward
            across the moor, there being three leagues betwixt the Hall
            and her father’s farm.

“It chanced that some little time later Hugo left his
            guests to carry food and drink—with other worse things,
            perchance—to his captive, and so found the cage empty and
            the bird escaped.  Then, as it would seem, he became as one
            that hath a devil, for, rushing down the stairs into the
            dining-hall, he sprang upon the great table, flagons and
            trenchers flying before him, and he cried aloud before all
            the company that he would that very night render his body
            and soul to the Powers of Evil if he might but overtake the
            wench.  And while the revellers stood aghast at the fury of
            the man, one more wicked or, it may be, more drunken than
            the rest, cried out that they should put the hounds upon
            her.  Whereat Hugo ran from the house, crying to his grooms
            that they should saddle his mare and unkennel the pack, and
            giving the hounds a kerchief of the maid’s, he swung them
            to the line, and so off full cry in the moonlight over the
            moor.
